### PR TITLE
Development

### PR DESCRIPTION
**Pull request by fatymahmed**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Great work team 👏
Your page looks awesome. You sure did a good job. Be we need to do some changes to make your project in line with Microverse guidelines. These changes are needed because of the importance of semantic HTML.

- Navigation bar

- [x] The navbar should be fixed positioning (only in the smaller breakpoint)

- Top Stories section

- [x] It should be wrapped around a pair of `section` HTML tags

- [x] It should have three stories, each one wrapped around a pair of `article`

- Latest News section

- [x] It should be wrapped around a pair of `section` HTML tags

- [x] It should have eight articles, each one wrapped around a pair of `article`

- Latest Funding section

- [x] It should be wrapped around a pair of `section` HTML tags

- [x] It should have three articles (4 in the larger breakpoint), each one wrapped around a pair of `article`

- Apps section and similar ones

- [x] It should be wrapped around a pair of `section` HTML tags

- [ ] It should have eight articles, each one wrapped around a pair of `article`

- Latest Deals section

- [ ] It should be wrapped around a pair of `section` HTML tags

- [ ] It should have eight articles, each one wrapped around a pair of `article`

Please kindly make these changes and submit for code review again.

**Comment by mosaaleb** [comment]
Reviewing

**Review by mosaaleb — APPROVED** [review]
### Congratulations @fatymahmed, @onedebos :clap:
#### All requirements are met, you can merge into master :+1: 

Good luck with the next projects

### Happy Coding :computer:

**Pull request merged**
